language: cpp

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -H. -Bbuild

script: cmake --build build

after_success:
  - coveralls --gcov-options '\-lp'
