language: cpp

addons:
  apt:
    packages: lcov

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -H.. -Bbuild -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

script: cmake --build build --config Debug

after_success:
  - coveralls --gcov-options '\-lp'
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
