language: cpp

addons:
  apt:
    packages: lcov

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -H.. -Bbuild -DCMAKE_BUILD_TYPE=Debug

script: cmake --build build --config Debug

after_success:
  - coveralls --gcov-options '\-lp'
