image: Visual Studio 2015

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" ..
  - cmake --build . --target ci
  
artifacts:
  - path: Debug/
    name: ci
