version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

       - run:
          name: tools
          command: 'apt-get update && apt-get install -y sudo gcc g++ cmake'
          
      - run:
          name: build
          command: 'cmake -H. -Bbuild && cmake --build build'
