version: 2

jobs:
  build:
    docker:
     - image: circleci/node:latest
    steps:
     - checkout
     - run: 'npm i coveralls codecov jest codacy-coverage'
     - run: 'node index.js'
     - run: 'node ./node_modules/jest/bin/jest --coverage && cp ./coverage/lcov.info coverage.lcov'
     - run: 'cat coverage.lcov | node ./node_modules/coveralls/bin/coveralls.js'
     - run: 'node ./node_modules/.bin/codecov'
     - run: 'cat coverage.lcov | node ./node_modules/codacy-coverage/bin/codacy-coverage.js'
     - run: 'tar -czf tarball.tgz README cov-int && curl --form token=$COVTOKEN --form email=$COVMAIL --form file=@tarball.tgz --form version="1.0.0" --form description="ci" https://scan.coverity.com/builds?project=ci249%2Fci'
