version: 2
orbs:
  codecov: codecov/codecov@1.0.2
workflows:
  main:
    jobs:
      build:
        docker:
          - image: debian:stretch
        steps:
          - checkout
          - run: 'apt-get update && apt-get install -y sudo gcc g++ cmake lcov'
          - run: 'cmake -H. -Bbuild && cmake --build build'
          - store_artifacts: 
              path: build/ci
              destination: ci
          - codecov/upload:
              file: {{ coverage_report_filepath }}
