version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 'apt-get update && apt-get install -y sudo gcc g++ cmake'
      - run: 'cmake -H. -Bbuild && cmake --build build'
