version: 2

jobs:
  build:
    docker:
     - image: circleci/node:latest
    steps:
     - checkout
     - run: 'npm i jest -g'
     - run: 'npm i coveralls codecov'
     - run: 'node index.js'
     - run: 'jest --coverage && cp ./coverage/lcov.info coverage.lcov'
     - run: 'cat coverage.lcov | ./node_modules/coveralls/bin/coveralls.js'
     - run: './node_modules/.bin/codecov'
