version: 2

jobs:
  run:
    docker:
     - image: circleci/node:latest
    steps:
     - checkout
     - run: 'node index.js'
     - run: 'coveralls --gcov-options "-lp"'
     - run: 'bash <(curl -s https://codecov.io/bash) | sed -E "s/token=[A-Fa-f0-9\-]+/token=[codecov token]/g" | sed -e "s/$CODECOV_TOKEN/[codecov token]/g"'
