version: 2

jobs:
  build:
    docker:
     - image: circleci/node:latest
    steps:
     - checkout
     - run: 'npm i coveralls codecov jest'
     - run: 'node index.js'
     - run: 'node ./node_modules/jest/bin/jest --coverage && cp ./coverage/lcov.info coverage.lcov'
     - run: 'cat coverage.lcov | node ./node_modules/coveralls/bin/coveralls.js'
     - run: 'node ./node_modules/.bin/codecov'
