image: Visual Studio 2015

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install/ ..
  - cmake --build . --target install
  
artifacts:
  - path: install/
    name: ci
