image: ubuntu

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install/ ..
  - cmake --build . --target install
 
after_build:
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

artifacts:
  - path: install/
    name: ci
